trigger:
- main

resources:
- repo: self

variables:
- group: EbayScraperEnvVariables
  # Update these variables with your own values
  dockerComposeFile: './docker-compose.yml'
  dockerRegistryServiceConnection: 'serviceconnection'#serviceConnectionName
  imageRepository: 'frontend,backend'#imageName
  containerRegistry: 'mushtaq96.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)'
  tag: '$(Build.BuildId)'


stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: DockerCompose@0
      displayName: Build services
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscriptionEndpoint: $(dockerRegistryServiceConnection)
        azureContainerRegistry: $(containerRegistry)
        dockerComposeFile: $(dockerComposeFile)
        action: 'Build services'
        additionalImageTags: $(tag)

    - task: DockerCompose@0
      displayName: Push services
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscriptionEndpoint: $(dockerRegistryServiceConnection)
        azureContainerRegistry: $(containerRegistry)
        dockerComposeFile: $(dockerComposeFile)
        action: 'Push services'
        additionalImageTags: $(tag)
