trigger:
- main

resources:
- repo: self

variables:
- group: EbayScraperEnvVariables
- name: dockerComposeFile
  value: './docker-compose.yml'
- name: dockerRegistryServiceConnection
  value: 'mushtaq96' # Update with your service connection name
- name: imageRepository
  value: 'frontend,backend' # Update with your image repository names
- name: containerRegistry
  value: 'mushtaq96.azurecr.io' # Update with your container registry
- name: dockerfilePath
  value: '$(Build.SourcesDirectory)'
- name: tag
  value: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: DockerCompose@0
      displayName: Build services
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscriptionEndpoint: $(dockerRegistryServiceConnection)
        azureContainerRegistry: $(containerRegistry)
        dockerComposeFile: $(dockerComposeFile)
        action: 'Build services'
        additionalImageTags: $(tag)

    - task: DockerCompose@0
      displayName: Push services
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscriptionEndpoint: $(dockerRegistryServiceConnection)
        azureContainerRegistry: $(containerRegistry)
        dockerComposeFile: $(dockerComposeFile)
        action: 'Push services'
        additionalImageTags: $(tag)
