version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - SENDER_MAIL=${SENDER_MAIL}
      - SENDER_PASSWORD=${SENDER_PASSWORD}
      - RECEIVER_MAIL=${RECEIVER_MAIL}
      - DATABASE_URL=sqlite:///./sql_app.db  # Use SQLite'  
