version: '1'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - SENDER_MAIL=${SENDER_MAIL}
      - SENDER_PASSWORD=${SENDER_PASSWORD}
      - RECEIVER_MAIL=${RECEIVER_MAIL}
    depends_on:
      - db
  db:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER='mushtaq96'
      - POSTGRES_PASSWORD='mushtaq96'
      - POSTGRES_DB=ebay
    volumes:
      - db-data:/var/lib/postgresql/data
      # first instance of "volumes" is used to create a named volume named "db-data" 
      # that is mounted to the "/var/lib/postgresql/data" directory inside the PostgreSQL container
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  db-data:
  